"""empty message

Revision ID: 11480d792864
Revises: 07b37de9b6b1
Create Date: 2022-12-22 16:13:55.272256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11480d792864'
down_revision = '07b37de9b6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
